#! /bin/bash

# update apmn-js version in the <apmn-js-examples> project

PWD="$(pwd)"
WORKDIR="$(pwd)/tmp"
EXAMPLES_DIR="$WORKDIR/apmn-js-examples"

# create work dir
mkdir -p "$WORKDIR"

git clone --depth=1 https://github.com/apmn-io/apmn-js-examples.git "$EXAMPLES_DIR"

cd "$EXAMPLES_DIR"

# update bower.json
TOOLKIT_VERSION="${TRAVIS_TAG:1}"
echo "Updating toolkit version to $TOOLKIT_VERSION"

sed -i -E "s#(\"apmn-js\": )\"[^\"]+\"#\1\"^$TOOLKIT_VERSION\"#" **/package.json
sed -i -E "s#/apmn-js@[^/]+/#/apmn-js@$TOOLKIT_VERSION/#" **/*.{html,md}

if [[ "x$SKIP_COMMIT" = "x" ]]; then

  git config user.email "$BPMN_IO_EMAIL"
  git config user.name "$BPMN_IO_USERNAME"
  git config push.default simple

  # add all resources
  git add -A
  git commit -m "chore(project): bump examples to $TRAVIS_TAG"
  git tag "$TRAVIS_TAG"
  git push -q "https://$GITHUB_AUTH@github.com/apmn-io/apmn-js-examples.git" &2>/dev/null
  git push --tags -q "https://$GITHUB_AUTH@github.com/apmn-io/apmn-js-examples.git" &2>/dev/null
else
  echo "Skipping commit (SKIP_COMMIT=$SKIP_COMMIT)"
fi

cd "$PWD"