#! /bin/bash

# bumps apmn-js and diagram-js dependencies in apmn-js-integration

PWD="$(pwd)"
WORKDIR="$(pwd)/tmp"
IT_DIR="$WORKDIR/apmn-js-integration"

# create work dir
mkdir -p "$WORKDIR"

git clone --depth=1 https://github.com/apmn-io/apmn-js-integration.git "$IT_DIR"

cd "$IT_DIR"

npm install --save apmn-js@latest apmn-moddle@latest

git config user.email "$BPMN_IO_EMAIL"
git config user.name "$BPMN_IO_USERNAME"
git config push.default simple

git add -A
git commit -m "chore(project): bump apmn-js to $TRAVIS_TAG"
git tag "$TRAVIS_TAG"
git push -q "https://$GITHUB_AUTH@github.com/apmn-io/apmn-js-integration.git" &2>/dev/null
git push --tags -q "https://$GITHUB_AUTH@github.com/apmn-io/apmn-js-integration.git" &2>/dev/null

cd "$PWD"